import React from 'react'
const InpuField = () => {
    return (
        <div className='lg:border-l-2  border-[#FD5A2A]'>
            <div className='lg:mx-20 mx-5 my-5'>
                <form className='mt-5 text-white'>
                    <div class="relative w-full min-w-[200px] h-10 mb-5">
                        <input
                            class="peer w-full h-full bg-transparent  text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200  focus:border-2 border-2 hover:border-[#FD5A2A]  border-gray-300 focus:border-t-transparent text-sm px-3 py-2.5 rounded-md border-blue-gray-200 focus:border-[#FD5A2A]"
                            placeholder=" " required /><label
                                class="flex w-full h-full text-gray-400 select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-tight peer-focus:leading-tight peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 peer-placeholder-shown:before:border-transparent before:rounded-tl-md before:border-t peer-focus:before:border-t-2 before:border-l peer-focus:before:border-l-2 before:pointer-events-none before:transition-all peer-disabled:before:border-transparent after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 peer-placeholder-shown:after:border-transparent after:rounded-tr-md after:border-t peer-focus:after:border-t-2 after:border-r peer-focus:after:border-r-2 after:pointer-events-none after:transition-all peer-disabled:after:border-transparent peer-placeholder-shown:leading-[3.75] text-blue-gray-400 peer-focus:text-[#FD5A2A] before:border-blue-gray-200 peer-focus:before:!border-[#FD5A2A] after:border-blue-gray-200 peer-focus:after:!border-[#FD5A2A]">Name *
                        </label>
                    </div>
                    <div class="relative w-full min-w-[200px] h-10 mb-5">
                        <input
                            class="peer w-full h-full bg-transparent  text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200  focus:border-2 border-2 hover:border-[#FD5A2A]  border-gray-300 focus:border-t-transparent text-sm px-3 py-2.5 rounded-md border-blue-gray-200 focus:border-[#FD5A2A]"
                            placeholder=" " required /><label
                                class="flex w-full h-full text-gray-400 select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-tight peer-focus:leading-tight peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 peer-placeholder-shown:before:border-transparent before:rounded-tl-md before:border-t peer-focus:before:border-t-2 before:border-l peer-focus:before:border-l-2 before:pointer-events-none before:transition-all peer-disabled:before:border-transparent after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 peer-placeholder-shown:after:border-transparent after:rounded-tr-md after:border-t peer-focus:after:border-t-2 after:border-r peer-focus:after:border-r-2 after:pointer-events-none after:transition-all peer-disabled:after:border-transparent peer-placeholder-shown:leading-[3.75] text-blue-gray-400 peer-focus:text-[#FD5A2A] before:border-blue-gray-200 peer-focus:before:!border-[#FD5A2A] after:border-blue-gray-200 peer-focus:after:!border-[#FD5A2A]">Company Name *
                        </label>
                    </div>
                    <div class="relative w-full min-w-[200px] h-10 mb-5">
                        <input
                            class="peer w-full h-full bg-transparent  text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200  focus:border-2 border-2 hover:border-[#FD5A2A]  border-gray-300 focus:border-t-transparent text-sm px-3 py-2.5 rounded-md border-blue-gray-200 focus:border-[#FD5A2A]"
                            placeholder=" " required /><label
                                class="flex w-full h-full text-gray-400 select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-tight peer-focus:leading-tight peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 peer-placeholder-shown:before:border-transparent before:rounded-tl-md before:border-t peer-focus:before:border-t-2 before:border-l peer-focus:before:border-l-2 before:pointer-events-none before:transition-all peer-disabled:before:border-transparent after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 peer-placeholder-shown:after:border-transparent after:rounded-tr-md after:border-t peer-focus:after:border-t-2 after:border-r peer-focus:after:border-r-2 after:pointer-events-none after:transition-all peer-disabled:after:border-transparent peer-placeholder-shown:leading-[3.75] text-blue-gray-400 peer-focus:text-[#FD5A2A] before:border-blue-gray-200 peer-focus:before:!border-[#FD5A2A] after:border-blue-gray-200 peer-focus:after:!border-[#FD5A2A]">Company Email Address *
                        </label>
                    </div>
                    <div class="relative w-full min-w-[200px] h-10 mb-5">
                        <input
                            class="peer w-full h-full bg-transparent  text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200  focus:border-2 border-2 hover:border-[#FD5A2A]  border-gray-300 focus:border-t-transparent text-sm px-3 py-2.5 rounded-md border-blue-gray-200 focus:border-[#FD5A2A]"
                            placeholder=" " /><label
                                class="flex w-full h-full text-gray-400 select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-tight peer-focus:leading-tight peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 peer-placeholder-shown:before:border-transparent before:rounded-tl-md before:border-t peer-focus:before:border-t-2 before:border-l peer-focus:before:border-l-2 before:pointer-events-none before:transition-all peer-disabled:before:border-transparent after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 peer-placeholder-shown:after:border-transparent after:rounded-tr-md after:border-t peer-focus:after:border-t-2 after:border-r peer-focus:after:border-r-2 after:pointer-events-none after:transition-all peer-disabled:after:border-transparent peer-placeholder-shown:leading-[3.75] text-blue-gray-400 peer-focus:text-[#FD5A2A] before:border-blue-gray-200 peer-focus:before:!border-[#FD5A2A] after:border-blue-gray-200 peer-focus:after:!border-[#FD5A2A]">Mobile No *
                        </label>
                    </div>
                    <div class="relative w-full min-w-[200px] h-10 mb-5">
                        <input
                            class="peer w-full h-full bg-transparent  text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200  focus:border-2 border-2 hover:border-[#FD5A2A]  border-gray-300 focus:border-t-transparent text-sm px-3 py-2.5 rounded-md border-blue-gray-200 focus:border-[#FD5A2A]"
                            placeholder=" " required /><label
                                class="flex w-full h-full text-gray-400 select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-tight peer-focus:leading-tight peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 peer-placeholder-shown:before:border-transparent before:rounded-tl-md before:border-t peer-focus:before:border-t-2 before:border-l peer-focus:before:border-l-2 before:pointer-events-none before:transition-all peer-disabled:before:border-transparent after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 peer-placeholder-shown:after:border-transparent after:rounded-tr-md after:border-t peer-focus:after:border-t-2 after:border-r peer-focus:after:border-r-2 after:pointer-events-none after:transition-all peer-disabled:after:border-transparent peer-placeholder-shown:leading-[3.75] text-blue-gray-400 peer-focus:text-[#FD5A2A] before:border-blue-gray-200 peer-focus:before:!border-[#FD5A2A] after:border-blue-gray-200 peer-focus:after:!border-[#FD5A2A]">Industries
                        </label>
                    </div>
                    <div class="relative w-full min-w-[200px]  mt-4 ">
                        <textarea
                            class="peer w-full h-full resize-none lg:h-[6rem] bg-transparent  text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200  focus:border-2 border hover:border-[#FD5A2A]  border-gray-300 focus:border-t-transparent text-sm px-3 py-2.5 rounded-md border-blue-gray-200 focus:border-[#FD5A2A]"
                            placeholder=" " required></textarea><label
                                class="flex w-full h-full text-gray-400 select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-tight peer-focus:leading-tight peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 peer-placeholder-shown:before:border-transparent before:rounded-tl-md before:border-t peer-focus:before:border-t-2 before:border-l peer-focus:before:border-l-2 before:pointer-events-none before:transition-all peer-disabled:before:border-transparent after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 peer-placeholder-shown:after:border-transparent after:rounded-tr-md after:border-t peer-focus:after:border-t-2 after:border-r peer-focus:after:border-r-2 after:pointer-events-none after:transition-all peer-disabled:after:border-transparent peer-placeholder-shown:leading-[3.75] text-blue-gray-400 peer-focus:text-[#FD5A2A] before:border-blue-gray-200 peer-focus:before:!border-[#FD5A2A] after:border-blue-gray-200 peer-focus:after:!border-[#FD5A2A]">Special Note
                        </label>
                    </div>
                    <div className='flex mt-6 lg:mt-10'>
                        <button type='submit' className='mx-auto px-6 py-3 rounded-md font-semibold duration-500  text-white  hover:text-[#FD5A2A]  text-sm hover:bg-white  bg-[#FD5A2A] border-2 hover:border-[#FD5A2A] uppercase' >Request now</button>
                    </div>
                </form>
            </div>
        </div>
    )
}

export default InpuField
